### ISSUE TITLE
is this project completed?

### ISSUE THREAD

**Issue by lcko1012** [trinhdvt/lang-thang#14]

**Comment by lcko1012** [comment]
I hope you can develop more about replying to comments

**Comment by trinhdvt** [comment]
> I hope you can develop more about replying to comments

Thank you for your request, I appreciate it. But I'm inactive now, so I'll take a look in next month to see if it's possible or not.

**Comment by trinhdvt** [comment]
@lcko1012 Hi! I have changed some backend APIs to support this new feature, but my teammate seems inactive now. So it would be nice if you can I help me with this 😊. For more details, you can check out the new document at [here](https://github.com/trinhdvt/lang-thang/blob/master/docs/API/Comment_API.md#l%E1%BA%A5y-ra-danh-s%C3%A1ch-c%C3%A1c-comment-c%E1%BB%A7a-m%E1%BB%99t-b%C3%A0i-vi%E1%BA%BFt-b%E1%BA%B1ng-id-ho%E1%BA%B7c-slug) and [here](https://github.com/trinhdvt/lang-thang/blob/master/docs/API/Comment_API.md#th%C3%AAm-m%E1%BB%99t-comment) or maybe the [lastest commit](https://github.com/trinhdvt/lang-thang/commit/9853c54fd519256edf3075b3a89929b47f81e383) can provide some useful information.
